version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aws-test-backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend/data:/app/data # Mount data folder to persist/update jsons without rebuilding
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: aws-test-frontend
    ports:
      - "80:80" # Maps the frontend to localhost:80
    depends_on:
      - backend
    restart: unless-stopped
